### ISSUE TITLE
I can't find Wire.transfer(address, &subAddress, 1, dest, count);

### ISSUE THREAD

**Issue by adrian-taralunga** [kriswiner/BMA280#1]
Hey, thanks for creating this library. 
I have one issue and I'm struggling with it. Can you point me to the right wire library because I seem to have an issue finding Wire.transfer(address, &subAddress, 1, dest, count); 

The error is `'class TwoWire' has no member named 'transfer`

Thanks

**Comment by kriswiner** [comment]
This function is only for the STM32L4 Arduino core. You are going to have
to use a different Wire.h if you are using something else. Try the ESP8285
example, it is more generic.

**Comment by adrian-taralunga** [comment]
@kriswiner thanks, I eventually figure it out by recreating the functions for my board (esp8266) and it works. Thanks for the great work :)

**Comment by carlosjs** [comment]
> @kriswiner thanks, I eventually figure it out by recreating the functions for my board (esp8266) and it works. Thanks for the great work :)
Hey, would you please share the new functions you recreated? Thanks both of you
