### ISSUE TITLE
Could not find formulas in data sheet.

### ISSUE THREAD

**Issue by rbhom** [kriswiner/BMA280#3]
Hi Kriswiner,

Thanks for this library.
This might be a dumb question, but am new bee to esp32 and embedded programming.
after reading Online sources got to know that all the formulas for particular sensor will be available in data sheet and how to map the register for reading and writing data from sensors.
coming to your library i have few doubts.
it would really be helpful if you can take some time and list me page numbers from below datasheet for these formulas.

datasheet that i followed at : https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bma280-ds000.pdf

doubts:

--> In getAres() 2.0f(range)/8192.0f (i understand it is 2 ^ 13) but where is this formula in data sheet ?

-->how the value of FCres = 7.8125f; (i tried doing it 2.0f/2^13) calculated ? same for self test float STres = 4000.0f/8192.0f; ?

--> after retrieving the raw values and converted to ares, we are dividing by 4 (i got this) but multiplying it with 1000*ax etc, why ? is this available in data sheet or just basic calculation ?

Thanks,
Ravi kiran B.

**Comment by kriswiner** [comment]
These are all basic calculations. See Table 5 page 19.

For a 14 bit sensor and +/-2 g full range, the resolution is 2/2^13 =
2/8192 = 0.244 mg as in Table 5.

For display, I want mg for highest resolution so 0.1 g * 1000 = 100 mg
since meaningful differences are ~10 mg or so. This is for convenience, etc.

**Comment by rbhom** [comment]
Thanks a lot kriswiner.
Sorry for late response.
how the value of FCres = 7.8125f; (i tried doing it 2.0f/2^13) calculated ? same for self test float STres = 4000.0f/8192.0f; ?
